/**
 * Generate dist/sw.js after a build.
 *
 * Hand-rolled rather than pulled from Workbox: the precache list is the set of
 * files Vite just emitted, which is a directory listing, and the caching rules
 * are two lines. A build-time dependency tree is not worth it here.
 *
 * The strategy is deliberately split:
 *
 * - Hashed assets (/assets/*) are immutable — their name changes when their
 *   content does — so they are served cache-first and never revalidated.
 * - The HTML document is network-first, falling back to cache. Cache-first on
 *   the document is how a PWA pins itself to an old version for ever: the
 *   browser keeps serving stale HTML that references assets it already has, and
 *   the user never sees an update.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
const base = process.env.BASE_PATH ?? '/';

/** Every emitted file, so the app works offline in full rather than in part. */
async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files = (await walk(dist))
  .map((f) => relative(dist, f).split('\\').join('/'))
  // standalone.html is a separate single-file artefact, not part of the app shell.
  .filter((f) => f !== 'sw.js' && f !== 'standalone.html');

const urls = files.map((f) => `${base}${f}`);
// Navigations resolve to the base itself, which is not a file on disk.
if (!urls.includes(base)) urls.unshift(base);

// A content hash means the cache name changes only when something actually
// changed, so an unchanged redeploy does not throw away a working cache.
const version = createHash('sha256')
  .update((await Promise.all(files.map((f) => readFile(join(dist, f))))).join('\u0000'))
  .digest('hex')
  .slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const CACHE = 'italiano-quotidiano-${version}';
const PRECACHE = ${JSON.stringify(urls, null, 2)};
const DOC = '${base}';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Documents: network first, so an update is picked up as soon as there is a
  // connection, with the cached shell as the offline fallback.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(DOC, copy));
          return response;
        })
        .catch(() => caches.match(DOC).then((cached) => cached || caches.match(request))),
    );
    return;
  }

  // Everything else is content-hashed and safe to serve from cache first.
  event.respondWith(
    caches.match(request).then(
      (cached) =>
        cached ||
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`;

// A service worker with a syntax error does not fail loudly — it simply never
// registers, and offline support disappears without anyone noticing. Parse it
// before writing it.
try {
  new Function(sw);
} catch (error) {
  throw new Error(`Generated service worker is not valid JavaScript: ${error.message}`);
}

await writeFile(join(dist, 'sw.js'), sw, 'utf8');
console.log(`dist/sw.js — ${urls.length} files precached, cache italiano-quotidiano-${version}`);
